name: analysis
run-name: Running Static Analysis Tools
on: [push]
jobs:
  run_static_analysis_hw2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: autopep8
      run: |
        pip install --upgrade autopep8
        find -type f -name '*.py' ! -path '*/migrations/*' -exec autopep8 --in-place --aggressive --aggressive '{}' \;
    - name: pyright
      run: |
        pip install pyright
        find -type f -name '*.py' ! -path '*/migrations/*' -exec pyright '{}' \;
    # - name: pylint
    #   run: |
    #     pip install pylint
    #     find -type f -name '*.py' ! -path '*/migrations/*' -exec pylint '{}' \;
    - uses: Silleellie/pylint-github-action@v2
      with:
        # Path of the package(s) or python file(s) to lint, relative to the repository root. 
        # If more than one package (or python file) should be linted, simply specify all of them 
        # with the multi-line notation like so:
        # lint-path: |
        #   src
        #   other_src
        #   main.py
        #   ...
        # 
        # Required
        lint-path:
          src
          hw2/hw2_debugging.py
        
        # Version of the Python interpreter which will install all requirements of your project 
        # and lint the package(s) or python file(s) specified with the `lint-path` argument
        #
        # Required
        python-version: 3.x
        
        # Path of the README.md to update with the pylint badge, relative to the repository root.
        #
        # Optional, Default: README.md
        readme-path: README.md

        # Text to display in the badge
        #
        # Optional, Default: PyLint
        badge-text: PyLint

        # Color of the badge for pylint scores < 5.
        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
        #
        # Optional, Default: red
        color-bad-score: red

        # Color of the badge for pylint scores in range [5,8).
        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
        #
        # Optional, Default: orange
        color-ok-score: orange

        # Color of the badge for pylint scores in range [8,10).
        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
        #
        # Optional, Default: yellow
        color-good-score: yellow

        # Color of the badge for pylint scores == 10.
        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
        #
        # Optional, Default: brightgreen
        color-perfect-score: brightgreen
  